language: python
cache: pip
sudo: false
matrix:
  fast_finish: true
  include:
  - python: '3.6'
    env: DJANGO=2.2 DRF=3.9
  - python: '3.6'
    env: DJANGO=2.2 DRF=3.10
  - python: '3.6'
    env: DJANGO=2.2 DRF=3.11
  - python: '3.6'
    env: DJANGO=3.0 DRF=3.10
  - python: '3.6'
    env: DJANGO=3.0 DRF=3.11
  - python: '3.7'
    env: DJANGO=2.2 DRF=3.9
    dist: xenial
    sudo: true
  - python: '3.7'
    env: DJANGO=2.2 DRF=3.10
    dist: xenial
    sudo: true
  - python: '3.7'
    env: DJANGO=2.2 DRF=3.11
    dist: xenial
    sudo: true
  - python: '3.7'
    env: DJANGO=3.0 DRF=3.10
    dist: xenial
    sudo: true
  - python: '3.7'
    env: DJANGO=3.0 DRF=3.11
    dist: xenial
    sudo: true
  - python: '3.8'
    env: TOXENV=py38-flake8
  - python: '3.8'
    env: DJANGO=2.2 DRF=3.9
    dist: xenial
    sudo: true
  - python: '3.8'
    env: DJANGO=2.2 DRF=3.10
    dist: xenial
    sudo: true
  - python: '3.8'
    env: DJANGO=2.2 DRF=3.11
    dist: xenial
    sudo: true
  - python: '3.8'
    env: DJANGO=3.0 DRF=3.10
    dist: xenial
    sudo: true
  - python: '3.8'
    env: DJANGO=3.0 DRF=3.11
    dist: xenial
    sudo: true
install:
- pip install tox-travis python-coveralls
- pip install -r requirements.txt
script:
- tox
after_success:
- coverage run runtests.py --nolint
- coveralls
deploy:
  provider: pypi
  twine_version: 3.1.1
  user: __token__
  password:
    secure: RY3i1vCr64c34Ps7XAzHJxbdMQDJB6kPOdML9mceq9AM2HYWEz2vJG925h8s1+MEKx3kKbjuoqlxNt/FiyDfQCcQe/NUH5FfI1ZQ6Y1T/AerIS3XcmSEid/IYPRAOVT7qJzV0dmnP9Kba6piOK0soTrkkddYyVQ3jwlHM0RQjySX1f0CdC99Rn2ROwPXResmnBvbvaD8jzws0xoOP7OND6sekozs47ro3UQdYx6Iz9IkJx3M0olUofPzt1JDX5O/arE4R482sAHyUykBITkOFQQ4DGrOF6CEDJCYp8cSdsEXjbKKQHYPoFjykJdePYOX7YvJe6W9Lrrr8huFflKQMK2cBFXsB5dYx3WSAKk9xjvuoD5PlKKn/LDmQIMZTVZbRN0K4jvb7SGF1LyvaYBkW0ck3NHL8DtH9NW7FD/tBC60+3qoQqMvDRtbpC26R5CvM2aM7IgqqF4Lx9bGsNEqHYZkn9WIH04rOpCxYcmT19LHKpJvnAHlyTt7gnMGAbjqdoLPD/iD2ZVH2Bf6BflydBDuszY6hpeIjtkazhiW+Ah40d5TUr/nr9IFSDGFLgIx7BUJApeUi7PtP43yRwaQDQWtEVH4YAAcusjOwfjXBF1DuWplnhQg3sJeMMmU3Ub5uf1z642WFctqGRpDRkPdyQ8TZuSTm9VRJmuS+FSNApM=
  distributions: sdist bdist_wheel
  on:
    tags: true
    repo: lingster/drf-api-tracking
