site_name: drf-api-tracking
site_description: Utils to log Django Rest Framework requests to the database
repo_url: https://github.com/lingster/drf-api-tracking
site_dir: html
extra_css:
  - css/extra.css
